title: "N4BM Security Blog"        
description: "Exploring Cybersecurity, Tools, and Techniques"  
baseurl: ""                      
url: "https://n4bm.github.io" 

remote_theme: "jekyll-theme-cayman"
plugins:
  - jekyll-feed                         
  - jekyll-seo-tag                      
  - jekyll-sitemap                      

header_pages:
  - index.html                           
  - about.html                           
  - posts.html                           

social_links:
  github: "https://github.com/n4bm" 

author:
  name: "N4BM"                  
  bio: "Security Enthusiast"  
